version: '3.7'



services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: tacos
      MYSQL_USER: maxk
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  app-server:
    restart: always
    environment:
      DATABASE_HOST: tacos
      DATABASE_USER: maxk
      DATABASE_PASSWORD: 12345
      DATABASE_NAME: tacos
      DATABASE_PORT: 3306
    depends_on:
      - db
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile

